// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtk-81Q7wObTOd_fF1_ko-h3d-wewZSEA',
    appId: '1:327034066856:web:8f75e48f0abed52e6daf9d',
    messagingSenderId: '327034066856',
    projectId: 'petdog-store',
    authDomain: 'petdog-store.firebaseapp.com',
    storageBucket: 'petdog-store.appspot.com',
    measurementId: 'G-04JGV5C46N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmK0AWlmo_NLQ8DZp-4GPZeatJD7D4jk0',
    appId: '1:327034066856:android:243d23083735b63a6daf9d',
    messagingSenderId: '327034066856',
    projectId: 'petdog-store',
    storageBucket: 'petdog-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfwJtwsobMOaYR3_BiplwlvFdjTP7r6Y',
    appId: '1:327034066856:ios:ed7cb059075e1bae6daf9d',
    messagingSenderId: '327034066856',
    projectId: 'petdog-store',
    storageBucket: 'petdog-store.appspot.com',
    iosBundleId: 'com.example.petStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXfwJtwsobMOaYR3_BiplwlvFdjTP7r6Y',
    appId: '1:327034066856:ios:0f9d672b0f8040896daf9d',
    messagingSenderId: '327034066856',
    projectId: 'petdog-store',
    storageBucket: 'petdog-store.appspot.com',
    iosBundleId: 'com.example.petStore.RunnerTests',
  );
}
